### PR TITLE
MIP1: Equihash PoW support

### PR DESCRIPTION
**Pull request by 8bitcoder**
MIP1: Equihash PoW support

Note additional dependency on libsodium.

Retire Skein for Equihash using BIP9 version bit 3.

Todo

- Test compatibility with existing mining software.

### CODE REVIEW

**Comment by cryptapus** [comment]
Concept ACK

I suppose your intention is this should be post 0.14.2.4?

**Comment by 8bitcoder** [comment]
Post 0.14.2.4 yes.

This implementation allows us to start testing. Start/stop dates will be updated after we're satisfied with testing.

**Comment by 8bitcoder** [comment]
@roarde The current Equihash implementation should be compatible with the version used by ZCash. Not tested with any existing mining software yet.

**Comment by cryptapus** [comment]
I've found that same "ZcashPoW" in all the mining software I've seen, so altering that string in 28d9fec should be a simple edit for the miners. However, chaning the length beyond 8 char may be an issue.

**Pull request merged**
