### PR TITLE
0.14.xmy

### PR DESCRIPTION
**Pull request by cryptapus**
Does build, some floating point errors in some of the pow.cpp functions

### CODE REVIEW

**Comment by cryptapus** [comment]
I've been following some of the work going on in Unitus, I had started on it a while ago, but now this is heavily influenced from unitus master.

**Comment by cryptapus** [comment]
mainnet and testnet now sync, qt is working, some errors in tests still.

To build:

    ./autogen.sh
    ./configure (--with-incompatible-bdb)
    make (-jx)

**Comment by cryptapus** [comment]
The alert system in 0.11 clients must be disabled for testnet to work, here is a diff:


[out.txt](https://github.com/myriadteam/myriadcoin/files/1265232/out.txt)

**Comment by nzsquirrell** [comment]
Commit completed via 710a254d29b4711ced74338ad73f8c29fff59ad2 and 13db0be2e2d01036f9df7308f2932bf38f19d418

**Pull request closed without merging**
