### PR TITLE
Proposal: MIP3 - Longblocks

### PR DESCRIPTION
**Pull request by cryptapus**

### CODE REVIEW

**Comment by cryptapus** [comment]
I am proposing to increase Myriadcoin's block time to a much higher value. Originally, my thinking was to do this immediately. However I expect there to be some resistance so I've attempted to scale in the block time increase to give layer 2 alternatives more time to develop.

**Comment by 8bitcoder** [comment]
Concept ACK. 

Will review code later.

**Comment by 8bitcoder** [comment]
Reviewed, looks correct.

**Comment by cryptapus** [comment]
Thanks. I would like to fix some tests, then will include this in v0.14.3.1.

**Comment by cryptapus** [comment]
tests will fail until after activation cleanup

**Comment by cryptapus** [comment]
I'm not particularly happy with subsidy interval 12. There appears to be a 4 sat error as can be seen in main_tests. The best way I can think to correct is to return the correct value like we do for tail emission. Thoughts?

**Comment by 8bitcoder** [comment]
What happens when you do:

nSubsidy >>= halvings;

after:

nSubsidy *= 2 
nSubsidy *= 4
nSubsidy *= 8

i.e. first do the multiply then the shr.

This should result in more precise rounding.

**Comment by cryptapus** [comment]
Yes, that appears to work. Good lesson in rounding errors, thanks!

**Pull request merged**
