### PR TITLE
post MIP4 and MIP5 BIP9 fork cleanup

### PR DESCRIPTION
**Pull request by cryptapus**
This PR cleans up the MIP4 (Argon2D) and MIP5 (openssl bignum removal, issue #42 ) BIP9 consensus rules, locking in the fork height in preparation for future work. This is slated for `v0.16.4.1`

**note** as stated in #133 this will give a different `chainwork` than `v0.16.4.0` and the suspected reason is that we are now using the nthRoot product rule for all blocks that use `GetGeometricMeanPrevWork()`. However, since we are using the same calculation at the chaintip the risk of a fork is mitigated. Please double check my work here, I propose a soft release and request miner feedback on orphans.

With the removal of openssl bignum.h, I get the following startup `chainindex` loading speed increase: 

    i7-3770 with SSD:
    120sec -> 101sec

Future work may be to optimize a "approximate" nthRoot calculation for more speed improvement.

### CODE REVIEW

**Comment by nzsquirrell** [comment]
Looks good. Only thought - do we still need to check for libssl in configure.ac ? the only requirement i can find for openssl/ssl.h is in qt/test/test_main.cpp. Probably a non issue however.

**Comment by cryptapus** [comment]
As I recall there are some uses of openssl still in tests that are just now being removed upstream. I would propose that we keep that for test functionality and follow upstream's removal path.

**Comment by 8bitcoder** [comment]
Looks good. Ack.

**Comment by cryptapus** [comment]
Will add a checkpoint and plan release of `v0.16.4.1` in ~2weeks

**Comment by roarde** [comment]
Reminder: When releasing, an annotated tag should be used. Those who follow by updating a clone shouldn't have to use the "-t" pull option to get tags for releases.

**Comment by cryptapus** [comment]
@roarde request noted, I need to do some experimentation on another repo first to see how it works with the typical github+gitian release flow. But at least I'll make an attempt this time.

**Pull request merged**
